### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jthistle** [jthistle/tabby#1]
## Features to implement

- [x] bar resizing (doubling/halving length _and_ inserting chords)
- [ ] range selection with normal selection actions
- [x] read and write!
- [x] addition of extra elements to score (e.g. text) - requires cursor rework
- [ ] annotations above bar locked to certain chords (e.g. `S`, `P`)
- [x] informative undos (i.e. names for undo actions)
- [ ] a proper 'new tab' system

## Refactors needed

- [x] probably need to set up a proper system that maps hotkeys to actions
- [x] make some getter functions into `@property`s, and standardise that
- [x] restructure the ui system so that there is a global controller that takes the place of the current `Editor`, and which holds the header, the editor, and the console. The help message should no longer be a charge of the editor, but should instead be in this global container and shown instead of the editor when necessary.
- [ ] I hate hate hate the way I've bollocksed up the layout system with regards to the cursor, and it needs a refactor. Their should be some kind of positioning model from which the cursor can look up its screen position, instead of having to relayout each time the cursor is moved.

## Fixes

- [x] offscreen content
- [x] help is still broken
- [ ] the plaintext tab reader should read annotations properly

## Chores

- [ ] write some docs
- [x] set up a build system
- [ ] tests :(
- [ ] probably comment more things
- [ ] localisation? 

## Stretch goals

(i.e. stuff that probably won't happen, but I'd love to do in the future)

- [x] automatic parsing of existing tabs
- [x] playback of a selected chord
- [ ] short tutorial
